name: microservices

services:
  song-service:
    deploy:
      replicas: 2
    env_file:
      - .env
    build: ./song
#    ports:
#      - 8092-8093:8092
    depends_on:
      - db-song
      - eureka
    environment:
      DOCKER_EUREKA: eureka
      DOCKER_DB: song-db

  resource-service:
    env_file:
      - .env
    build: ./resource
#    ports:
#      - 8095:8091
    depends_on:
      - db-resource
      - eureka
    environment:
      DOCKER_EUREKA: eureka
      DOCKER_DB: resource-db
      
  eureka:
    build: ./eureka-server
    ports:
      - 8761:8761
        
  gateway:
    build: ./gateway
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      DOCKER_EUREKA: eureka
  
  db-song:
     hostname: song-db
     image: postgres:16-alpine
     volumes:
       - ./init-scripts/song_db/init.sql:/docker-entrypoint-initdb.d/db.sql
     environment:
       POSTGRES_USER: ${song_db_user}
       POSTGRES_PASSWORD: ${song_db_password}
       POSTGRES_DB: ${song_db_name}
       
  db-resource:
    hostname: resource-db
    image: postgres:16-alpine
    volumes:
      - ./init-scripts/resource_db/init.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: ${resource_db_user}
      POSTGRES_PASSWORD: ${resource_db_password}
      POSTGRES_DB: ${resource_db_name}