scrape_configs:
  - job_name: 'microservice-song'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus' ##prometheus endpoint
    static_configs:
      - targets: 
        - song-service:8092
  - job_name: 'microservice-storage'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - storage-service:8096
  - job_name: 'microservice-resource'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - resource-service:8091
  - job_name: 'microservice-resource-processor'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - resource-processor-service:8093