server:
  port: 8888
  
eureka:
   client:
     serviceUrl:
       defaultZone: http://${DOCKER_EUREKA:localhost}:8761/eureka

spring:
  application:
    name:
      gateway
  cloud:
    gateway:
      routes:
        - id: songModule
          uri: lb://song
          predicates:
            - Path=/songs/**
        - id: resourceModule
          uri: lb://resource
          predicates:
            - Path=/resources/**