server:
  port: 8888
  
eureka:
   client:
     serviceUrl:
       defaultZone: http://${DOCKER_EUREKA:localhost}:8761/eureka

spring:
  application:
    name:
      gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server:9000
  cloud:
    gateway:
      routes:
        - id: songModule
          uri: lb://song
          predicates:
            - Path=/songs/**
        - id: resourceModule
          uri: lb://resource
          predicates:
            - Path=/resources/**
        - id: authorizationModule
          uri: lb://authorization
          predicates:
            - Path=/oauth2/**
management:
  tracing:
    sampling:
      probability: 1

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans